spring:
  datasource:
    url: jdbc:mysql://localhost:3306/zhaild
    username: root
    password: 125188zld
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: provider-user

mybatis:
  type-aliases-package: com.spring.*.*.entity
  mapper-locations: classpath:mapper/*.xml

server:
  port: 8082

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8001/eureka/

